version: '3'
services:
    db:
        image: "postgres:9.6-alpine"
        volumes:
            - ./restaurants/src/main/resources/db:/docker-entrypoint-initdb.d:ro
        environment:
            - POSTGRES_DB=restaurants
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
        ports:
            - "5432:5432"

    app:
        build: ./restaurants
        ports:
            - "8888:8888"
            - "9990:9990"
        depends_on:
            - db
        command: java -jar /restaurants.jar -db.hostport=db:5432
